development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: RBlog_development
  pool:     5
  username: dbuser
  password: chuanzhi
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: RBlog_test
  pool:     5
  username: dbuser
  password: chuanzhi
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: RBlog_production
  pool:     50
  username: dbuser
  password: chuanzhi
  template: template0
